INSERT INTO TBL_HEADER VALUES (1,'make','Make',true);
INSERT INTO TBL_HEADER VALUES (2,'model','Model',true);
INSERT INTO TBL_HEADER VALUES (3,'price','Price',true);

INSERT INTO TBL_FILE_DETAILS VALUES (1,'Toyota','Celica',25000);
INSERT INTO TBL_FILE_DETAILS VALUES (2,'Ford','Mondeo',35000);
INSERT INTO TBL_FILE_DETAILS VALUES (3,'Porsche','Boxter',45000);
INSERT INTO TBL_FILE_DETAILS VALUES (4,'Maruti','Swift',55000);